# all: iter.o list.o main.o  
# 	g++ -o out main.cpp -std=c++17 -g
# iter.o:
# 	g++ -c iter.hpp -std=c++17	
# list.o:
# 	g++ -c list.hpp -std=c++17
# main.o: 
# 	g++ -c main.cpp -std=c++17

all: main.o 
	g++ -o out main.cpp -std=c++17 -g	
main.o: 
	g++ -Wall -c main.cpp -std=c++17
